Resolve verified contract names in decorated addresses
otterscan/otterscan pull request #1429
Opened 2023-10-28 03:33 UTC by sealer3

Currently looks like this:
![image](https://github.com/otterscan/otterscan/assets/125761775/81527bd3-e66b-4ab9-8868-1f5a731485b1)

Closes #1424

Keep in mind that if Otterscan gets popular, this feature might be abused.

2023-10-29 10:48 UTC, wmitsuda requested changes
cool, I think the colors worked really well.

can you make a storybook story for the new renderer? I made one for the ENSName component you can use as a template.

2023-10-31 03:52 UTC, sealer3 commented
I made the storybook Story, but it won't run until https://github.com/storybookjs/storybook/issues/22452 is resolved.

2023-10-31 18:25 UTC, wmitsuda commented
> I made the storybook Story, but it won't run until [storybookjs/storybook#22452](https://github.com/storybookjs/storybook/issues/22452) is resolved.

oh, f*ck... I don't mind then, will merge it because this feature looks cool and must be released.

2023-10-31 18:26 UTC, wmitsuda approved these changes

2023-10-31 18:26 UTC, merged