Use ABI of verified contracts to decode function selectors
otterscan/otterscan pull request #1443
Opened 2023-11-01 05:32 UTC by sealer3

Closes #1430

2023-11-02 17:52 UTC, wmitsuda requested changes
Hm, I think you didn't apply the Sourcify text color to the method text :)

2023-11-02 17:56 UTC, wmitsuda commented on src/use4Bytes.ts
> +  address?: string,
could you add a brief explanation in the function doc above about the new address param? because it seems unintuitive why it exists and I'm pretty sure we'll struggle in the future to remember its meaning.

2023-11-02 22:36 UTC, sealer3 commented
You're right. I'll add the Sourcify color and update the function doc.

2023-11-06 11:07 UTC, wmitsuda approved these changes
looks cool.

2023-11-06 11:08 UTC, merged