Show user notices and dev docs in decoded functions
otterscan/otterscan pull request #1580
Opened 2023-12-07 05:08 UTC by sealer3

Closes #1472

Preview (user + dev docs):
![image](https://github.com/otterscan/otterscan/assets/125761775/417c1b96-bc7b-4da5-be9a-48e3970afe31)

I didn't add much styling other than the dev label. The spacing might need adjustment.

2023-12-08 07:32 UTC, wmitsuda commented
I was just wondering if it is better to show that info in the input section or show it together with the "transaction action" section above.

what do you think? in the following example we would show the text: "Swaps `amountIn` of one token for as much as possible of another token" as an explanation of the `exactInputSingle` method.

<img width="727" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/a99784b9-e729-491f-86ff-7346ae8e740b">

2023-12-08 07:34 UTC, wmitsuda commented
for the record, I'm using the mainnet tx `0xa6d0a9ea478a7dc68db5749306f81fbc380825b53d088b878df83aef835838e7`   as a test.

2023-12-08 07:59 UTC, sealer3 commented
In my opinion, we should add the complete function signature near the top of the table and keep the documentation somewhere there, since whenever I read the input function parameters I also want to read the signature. Either way, I think you're right, the docs should go near the signature/function name. But in some cases you need the parameters to understand the docs, or want to reference the docs when reading the parameters.

2023-12-14 07:09 UTC, wmitsuda commented
The issue of adding the method signature is creating a readable string/UI for complex signatures (tuples, arrays, etc.).

On the other hand, what if we move the entire "Input data" section up, just after the "Transaction Action" section? and then move the function user/dev docs (not the params) to the "Transaction Action" section?

does it make more sense that way?

2023-12-28 19:07 UTC, sealer3 commented
Would something like this work better? I really think there should be a function signature near the parameters so you can quickly see the function without having to scroll through the input parameters to see the types. We can use compact types for tuples, like Etherscan does:

![image](https://github.com/otterscan/otterscan/assets/125761775/fe3a65e0-03ad-4f98-9238-d14f60cd7ee0)

Expanded to show the user doc:

![image](https://github.com/otterscan/otterscan/assets/125761775/8ac8753c-e79c-420b-b6a2-4521248532be)

Without compact types, the function signature looks more crowded but would be more convenient for developers:
![image](https://github.com/otterscan/otterscan/assets/125761775/cbe384ed-42be-4550-968e-527a352950a8) We could possibly show the full version when the help ? button is clicked.

2024-01-04 23:25 UTC, wmitsuda commented
I'm still not satisfied with the function sig proposal (idea makes senses, but the UI not good).

what if we merge the original proposal (user+dev docs) which we seemed to have reached consensus and discuss the function sig rework in another issue? (still no clear idea of good UI for that)

still, I think (user+dev docs for function) should be (for now) tied to the "transaction section" instead of the input block.

2024-01-05 06:43 UTC, sealer3 commented
Sure. I'm not sure if we should put the text in a container or not, but here is how it looks like without one:

User:
![image](https://github.com/otterscan/otterscan/assets/125761775/e0636fae-70af-4fef-acc5-42f048c0550d)

Dev:
![image](https://github.com/otterscan/otterscan/assets/125761775/6a21d0de-7869-477d-a2a8-93e1498a411c)

User+dev:
![image](https://github.com/otterscan/otterscan/assets/125761775/206d0b54-8f6e-472a-b7ae-9d8a4f3a4bfc)

2024-01-06 21:40 UTC, wmitsuda commented
I was thinking about hiding the explanation by default and have a "?" icon to display it like what happens in the param section. And have the "?" icon be displayed only when the natspec exists.

but it looks way better now.

wdyt?

2024-01-08 11:27 UTC, sealer3 commented
Okay, here's what it looks like now:

![image](https://github.com/otterscan/otterscan/assets/125761775/c540f15a-5928-4c89-bb13-a5bba480bb7c)

Open:

![image](https://github.com/otterscan/otterscan/assets/125761775/c43bb466-a649-4fe3-8e83-8e8865f17d41)

2024-01-09 21:09 UTC, wmitsuda requested changes

2024-01-09 21:09 UTC, wmitsuda commented on src/components/HelpButton.tsx
> +  return (
I think we can simplify this code by removing the ` { return` block since we are returning only JSX

2024-01-09 21:09 UTC, wmitsuda commented on src/execution/transaction/decoder/DecodedParamsTable.tsx
> +  return (
same here

2024-01-09 21:11 UTC, wmitsuda commented
> Okay, here's what it looks like now:
> 
> ![image](https://private-user-images.githubusercontent.com/125761775/294885152-c540f15a-5928-4c89-bb13-a5bba480bb7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzQ4ODcsIm5iZiI6MTcwNDgzNDU4NywicGF0aCI6Ii8xMjU3NjE3NzUvMjk0ODg1MTUyLWM1NDBmMTVhLTU5MjgtNGM4OS1iYjEzLWE1YmJhNDgwYmI3Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQyMTA5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ODMyM2MwMGNhNjkxNGQ5OTI2YmU2Yjg5MmMyMDIzN2U3YzFlNWZkZjViNDA1Y2Y1NjMzNzVhZDBmOWViMzc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g1SvraGh5nllCSFmJcrQJ4z540lNTXjwSmKwKe_0sLg)
> 
> Open:
> 
> ![image](https://private-user-images.githubusercontent.com/125761775/294885248-c43bb466-a649-4fe3-8e83-8e8865f17d41.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzQ4ODcsIm5iZiI6MTcwNDgzNDU4NywicGF0aCI6Ii8xMjU3NjE3NzUvMjk0ODg1MjQ4LWM0M2JiNDY2LWE2NDktNGZlMy04ZTgzLThlODg2NWYxN2Q0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQyMTA5NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWUzNTA5MTEwMTA1N2RlNzI3NmI0NjNmZTdlOWQ4YTJiZmYzMzcwNGE1NDc0NjU2MjI4MzYzOTI3ZjNlOGJkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bmV7kl1ajZ3BPAWOgKk7yvQrGNciMXrpNW9MwqQC0mI)

the `?`icon look a little odd, I think that's because it is aligned with the text baseline instead of vertically centered (I can see that by inspecting the gridlines with chrome devtools).

2024-01-09 21:12 UTC, wmitsuda commented
but it looks way better overall!

2024-01-09 21:17 UTC, wmitsuda commented
also, need to find a solution to make it respect linebreaks, see i.e.: tx 0xc54acb4d67da6071290f06c4aaaa5b895a7341528b2171690d20a3c11feeea25 on mainnet

<img width="1032" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/b8d879aa-0bf2-4a63-990d-a293725a8db1">

<img width="975" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/9d80b9f0-aa52-47f4-8d4e-308f3806dd0e">

2024-01-09 21:25 UTC, wmitsuda commented
I'm wondering if we can assume the docs are always markdown and use some markdown renderer...

2024-01-09 21:30 UTC, sealer3 commented
> also, need to find a solution to make it respect linebreaks, see i.e.: tx 0xc54acb4d67da6071290f06c4aaaa5b895a7341528b2171690d20a3c11feeea25 on mainnet

Unfortunately, the metadata file for that contract doesn't contain line breaks in the dev docs. Here's the metadata.json for that contract: 
https://repo.sourcify.dev/contracts/partial_match/1/0x8B227d72570D3EAd66014bCA8305CbeF7f90D1eE/metadata.json

I think the reason Solidity does this is that often lines are broken just to keep within a certain line width, but really we might want to open an issue in the Solidity compiler because two line breaks in a row clearly means there should be one there.

2024-01-09 21:51 UTC, sealer3 commented
> I'm wondering if we can assume the docs are always markdown and use some markdown renderer...

The official NatSpec page has an example using backticks for variables too. Although the NatSpec page doesn't mention anything about Markdown, I think Doxygen, from which NatSpec was inspired, supports Markdown formatting, so it probably came from there.

It would be interesting to learn the extent to which Markdown is used in these NatSpec comments in smart contracts.

2024-01-09 22:11 UTC, wmitsuda commented
> > also, need to find a solution to make it respect linebreaks, see i.e.: tx 0xc54acb4d67da6071290f06c4aaaa5b895a7341528b2171690d20a3c11feeea25 on mainnet
> 
> Unfortunately, the metadata file for that contract doesn't contain line breaks in the dev docs. Here's the metadata.json for that contract: https://repo.sourcify.dev/contracts/partial_match/1/0x8B227d72570D3EAd66014bCA8305CbeF7f90D1eE/metadata.json
> 
> I think the reason Solidity does this is that often lines are broken just to keep within a certain line width, but really we might want to open an issue in the Solidity compiler because two line breaks in a row clearly means there should be one there.

ugh... or maybe they didn't know how to encode the linebreaks inside the json... that's unfortunate...

2024-01-09 22:14 UTC, wmitsuda commented
what if we assume ". " (dot + whitespace) is a paragraph? and optionally allow the user to view the raw content? (downside is making the component more complex)

2024-01-09 22:40 UTC, sealer3 commented
> the `?`icon look a little odd, I think that's because it is aligned with the text baseline instead of vertically centered (I can see that by inspecting the gridlines with chrome devtools).

It might appear this way because the function name is size `text-xs` while the `?` icon is `text-sm`, but it's not explicitly aligned with the baseline (maybe through FontAwesome?). If I make the button `text-xs`, it will look like this:
![image](https://github.com/otterscan/otterscan/assets/125761775/c83f33ef-29d2-4460-9350-e4a824acc0d7)

2024-01-09 23:00 UTC, sealer3 commented
> what if we assume ". " (dot + whitespace) is a paragraph? and optionally allow the user to view the raw content? (downside is making the component more complex)

I'm not sure - there are many NatSpec comments that have more than one sentence but don't create a new paragraph, such as a Uniswap execute tx on mainnet: 0xefcf7fcc800ec038c06cc8abfbb2240600aa44cd50031fb1575ecf87b5db691e

2024-01-17 23:25 UTC, wmitsuda approved these changes

2024-01-17 23:26 UTC, wmitsuda commented
ok, let's merge it. I think we can still improve UI overall (for both method and input params formatting), but let's think about it separatelly (once I get some better inspiration :) )

2024-01-17 23:26 UTC, merged