Scroll tables horizontally in small viewport widths
otterscan/otterscan pull request #1733
Opened 2024-01-30 18:56 UTC by sealer3

Closes #291.

Uses `table-auto` and a combination of min width and max width classes to enable columns to expand as the viewport width increases.

The PendingResults component is no longer used. We should decide whether that animation should be used in PendingPage or not.

2024-02-04 05:49 UTC, wmitsuda commented
now that we can freely scroll horizontally, I'd suggest we increase the min column size for some columns, I think the defaults don't leave much space for them to be read, see below.

I think besides the Block column, all the other deserves some extra space for better readability.

<img width="871" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/f9641923-cb91-4b72-9fa2-e1e22c984ae5">

<img width="873" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/05761f05-de8b-4daa-977f-31ecd14b3d4b">

2024-02-04 05:49 UTC, wmitsuda requested changes

2024-02-04 05:49 UTC, wmitsuda commented on src/execution/address/GenericTransactionSearchResult.tsx
> +          <StandardScrollableTable isAuto={false}>
can we omit the isAuto param here and assume default for a cleaner code?

2024-02-04 14:04 UTC, sealer3 commented on src/execution/address/GenericTransactionSearchResult.tsx
> +          <StandardScrollableTable isAuto={false}>
Done

2024-02-04 18:32 UTC, sealer3 commented
The reason for the defaults was to reduce the amount of horizontal scrolling you would need to do on smaller screens, but I see the issue, especially with the method, value, and transaction fee columns.

I increased the column widths and fixed the width of some columns to space the contents better. Let me know if there are any specific columns you would like adjusted. Ideally we would be able to specify a maximum column width for certain columns, but so far I haven't found how to do that.

2024-02-10 18:12 UTC, wmitsuda commented
I'd like the tx hash/from/to columns to have the same size as before (see the comparison below), I don't mind if that means the tx fee gets pushed outsize the size + horizontal scrolling.

because they provide the most useful info IMHO in a search results, so we should maximize the ability of the user seeing what they mean (+ provide space for all the auxiliary UI decorations).

I think the other columns are ok. It is better to have horizontal scrolling, but the user can scroll and see more info, than not having scrolling, but the info is truncated.

before:

<img width="1421" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/e17707ec-8c64-452b-97d6-880526431144">


after:

<img width="1411" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/e6f17be0-b24c-49f1-80c7-e68ae8b22654">

2024-02-10 18:32 UTC, sealer3 commented
I've increased the transaction hash column to match the width of the from/to columns, and I've also made the transaction fee column variable in size but with a small enough default width that it's usually not shown completely, which gives more space to the other columns. Do you think it's okay if the transaction fee column is truncated?

2024-02-10 19:04 UTC, wmitsuda commented
I think we can leave the fee be truncated, as it currently is. I'm wondering if we could improve overall UX now that we have given up on trying to fit everything in a fixed resolution :)

but I'd like to think a little about it.

about the last adjustment: tx hash is bigger, but it seems it stole some space from the from/to columns :(

<img width="1411" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/e0d62292-8439-472e-b403-8c25571c3257">

2024-02-11 01:09 UTC, sealer3 commented
I've increased the column width of the from/to columns to compensate. It now takes a width of 1440 px to display all the content.

2024-02-11 15:17 UTC, wmitsuda commented
now the tx hash shrank a little 🥲

could you force it to be the same width as before the changes? (which is the hash text without the ellipsis "..." aligned to the "found" word)

<img width="1423" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/a316488b-6ad6-4941-b034-632d191484f9">

2024-02-12 15:25 UTC, sealer3 commented
Okay, the tx, from, and to columns are now expanded to match that (for a clientWidth of 1425 px):
![image](https://github.com/otterscan/otterscan/assets/125761775/e12adc35-e974-4250-a474-51f647e15da8)

2024-02-12 20:45 UTC, wmitsuda commented
ugh, got conflicted because I just merged the blob tx PR, rebase plz?

2024-02-13 01:35 UTC, sealer3 commented
Done

2024-02-13 20:35 UTC, wmitsuda commented
I just realized that now the gap between columns are way bigger than before (see below, the before screenshot is taken from sepolia.otterscan.io, you can use the browser inspect tool to compare the gaps more precisely).

I prefer the previous spacing, resulting in more dense info.

before:

<img width="1426" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/005152f4-ffb5-476b-8a70-0f38982393e9">

after:

<img width="1416" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/81e7f0a6-fdb5-419b-bfa1-203277a41a8f">

2024-02-13 20:38 UTC, wmitsuda commented
I think the other experimental views, like ERC20 search, etc, also have this bigger gap, but that's ok to reduce them as well, I consider it a bug I introduced in the past, i.e., same consistent spacing for all views across the app.

2024-02-14 05:35 UTC, sealer3 commented
I've reduced the padding between columns, and it now appears to have about the same gap as before. That noticeably helps!

2024-02-15 16:51 UTC, wmitsuda commented
yeah, but now it also decreased a few pixels from the margin before the first column.

before:

<img width="221" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/571be3cc-2b11-4673-a07f-436e7d1f0465">

after:

<img width="346" alt="image" src="https://github.com/otterscan/otterscan/assets/28685/c2d9983c-29a4-4c99-85e2-df9825d07cd0">

2024-02-16 02:12 UTC, sealer3 commented
Fixed: the horizontal padding around entire table rows is now identical to the way it was before.

2024-02-19 18:47 UTC, wmitsuda approved these changes
now we can merge it :)

2024-02-19 18:47 UTC, merged