Add initial inline address labeling tool
otterscan/otterscan pull request #1856
Opened 2024-03-11 05:25 UTC by sealer3

This tool uses `localStorage` to store address label changes. It has support for loading labels from external lists once a UI is created for that. `localStorage` changes take priority over those from external sources. As it stands, the interface does not let users "clear" labels set by external sources.

Example:
![image](https://github.com/otterscan/otterscan/assets/125761775/13c6376b-4589-4633-9265-17a718aaa660)
![image](https://github.com/otterscan/otterscan/assets/125761775/01ab989e-2586-475b-aedd-8377eeae7836)
![image](https://github.com/otterscan/otterscan/assets/125761775/2721b7b9-dd82-4505-985d-4fa10ed73d57)

This feature might be useful as is already, but I'm mainly looking for feedback. I'd also like to know how/where to store a list of external label sources (localStorage?) and where the user could manage this. I think we will also need a separate page for managing all of the user's `localStorage` custom labels at once. This might be accessible via an entry in the hamburger button dropdown.

Also, maybe standardizing the circle button into its own component would be useful to do...

Related: #245

2024-04-11 15:24 UTC, wmitsuda requested changes
I liked the functionality overall, there are some UI changes I'd like to have in the final version, but I think we don't need to worry about that, because for the prototype I'm happy with a functional interface we can use to test it.

I'd like to go in the following direction from now on, and ask for some small changes:

- Could we introduce some feature flag to enable this extra UI? It could be some WIP_<something> flag, it is only for us, don't need to document/publish it for now. Iit is for us. The reason for that is that we can merge it and keep working on it in small pieces, so we don't need to keep rebasing and dragging an ever growing PR.
- I think a "clear" or "delete" button would be useful to "reset" the state, so we don't need to manually delete the label during our tests.
- yeah, I agree that localStorage is not the ideal solution, it is ok for the purposes of this PR, but from now on we work/discuss the next step of our prototype. I actually have the idea in my mind, I'll share with you offline.

2024-04-27 14:54 UTC, sealer3 commented
I've hidden the labeler through a feature flag in the config (`WIP_customAddressLabels`) and also added a "clear all" button which wipes all custom address labels from localStorage, for development. To wipe a single address from the UI, edit the name, empty the name string, and click the check mark button to save.

2024-04-29 21:57 UTC, wmitsuda commented
note to myself: review this one after release 2.5 which is already full of features.

2024-04-30 21:45 UTC, wmitsuda approved these changes

2024-04-30 21:45 UTC, merged