Use Shiki as the syntax highlighter
otterscan/otterscan pull request #1966
Opened 2024-04-04 23:40 UTC by sealer3

Uses Shiki instead of react-syntax-highlighter for highlighting both Solidity and JSON (ABIs).

![image](https://github.com/otterscan/otterscan/assets/125761775/e1a8031e-0134-45e1-b914-e6ee1cc99e88)

Closes #1914, #1107, and #1886.

With Shiki you can copy code to the clipboard correctly. I haven't implemented line numbers yet; apparently that must be done manually. There might be some lag in loading the highlighted component. Shiki does not have much support for React, but at least it's possible following their version 1.0 rewrite.

2024-04-05 16:45 UTC, wmitsuda commented
just tried it out and looks excellent so far!

2024-04-05 16:46 UTC, wmitsuda commented
I think the decorations capabilities of this editor will allow us to make some interesting things in the future.

2024-04-09 13:51 UTC, sealer3 commented
Line numbers added:

![image](https://github.com/otterscan/otterscan/assets/125761775/06b55925-bd6e-4915-a943-32faf811629b)

2024-04-09 21:18 UTC, wmitsuda requested changes

2024-04-09 21:18 UTC, wmitsuda commented on src/execution/address/contract/HighlightedSolidity.tsx
> +import React from "react";
hm, could you collapse those imports?

2024-04-09 21:18 UTC, wmitsuda commented on src/execution/address/contract/HighlightedSolidity.tsx
> +export default React.memo(HighlightedSolidity);
or maybe import `memo` directly, so you don't need to import `React`?

2024-04-09 21:18 UTC, wmitsuda commented on src/execution/address/contract/HighlightedSource.tsx
> +import React, { useEffect, useState } from "react";
I think it is ok to remove the blank line above and let the import formatter reorg the lines

2024-04-09 21:18 UTC, wmitsuda commented on src/execution/address/contract/HighlightedSource.tsx
> +export const getOrCreateHighlighter = async (): Promise<HighlighterCore> => {
add a blank line before the export for better readability, please :)

2024-04-09 21:18 UTC, wmitsuda commented on src/execution/address/contract/RawABI.tsx
> +  return (
I think this code can be simplified by removing the "{ return {" since the is no code, only a tag, like the one who is being replaced.

2024-04-09 22:22 UTC, wmitsuda approved these changes

2024-04-09 22:22 UTC, merged