Show address transaction count for EOAs
otterscan/otterscan pull request #2153
Opened 2024-06-01 02:31 UTC by sealer3

Closes #744 

Adds an address's transaction count next to the page transaction count. It's only shown for EOAs.

![image](https://github.com/otterscan/otterscan/assets/125761775/4591d78a-f40e-4610-915b-bf03c7140342)

There's possibly other text that would fit here, such as using "X outgoing transactions" instead.

2024-06-07 20:19 UTC, wmitsuda commented
I feel like this info should be in the previous section, below or at the right of the balance box.

it doesn't mix well with the pagination stuff, it feels in the wrong place.

2024-06-07 20:21 UTC, wmitsuda requested changes
let's try to improve this info placement

2024-06-10 04:10 UTC, sealer3 commented
Okay. I don't think it deserves its own line below Balance - and we would have to stop it from page jumping if we put it below anyway. It's not easy to come up with other places where it would fit... the closest I'm thinking of is some kind of nonce-like indicator at the subtitle line. What do you think about that? Imagine a green nonce box (with the up arrow) to the right of the address label.

The reason I had it next to the pagination is that the transaction count gives you a lower bound on the total number of transactions in the table.

2024-06-13 21:46 UTC, wmitsuda commented
put it on the right? make it half and half panel

2024-06-18 22:27 UTC, sealer3 commented
> put it on the right? make it half and half panel

Exactly half?
![image](https://github.com/otterscan/otterscan/assets/125761775/e46d7b1b-6a56-4614-b5f8-dd39b596077f)


Or thirds?
![image](https://github.com/otterscan/otterscan/assets/125761775/af4eaa5a-c5ff-4093-ae75-ba3de79b8226)

2024-06-19 06:13 UTC, wmitsuda commented
half looks better?

2024-06-19 18:27 UTC, wmitsuda commented
that somehow still feels a little odd, but the feature is good. I think we'll eventually make changes in the layout in the future.

2024-06-19 18:27 UTC, wmitsuda approved these changes

2024-06-19 18:28 UTC, merged