Refactor config loading
otterscan/otterscan pull request #2225
Opened 2024-06-19 05:54 UTC by wmitsuda

Current config/probing code is very messy, tried to make it a little less messy :)

- Replaced the useEffect-based setup code with react-router's data loaders.
- I think the code got a little more easier to understand, also made it more separated and add some docs.
- Visually speaking it looks like it got a little faster.

2024-06-19 15:30 UTC, sealer3 requested changes

2024-06-19 15:30 UTC, sealer3 commented on src/useProvider.ts
> +  const probeOtsAPI = provider.send("ots_getApiLevel", []);
We are no longer checking the API level unless one of these calls returns an error response.

For example, if ots_getApiLevel returns 5, no error is shown anymore.

To include this check again here, you can change this Promise to one that wraps this check around the provider.send.

2024-06-19 15:30 UTC, sealer3 commented on src/useChainInfo.ts
> +  // TODO: check the assertions
I think it would be helpful to resolve the TODO now.

2024-06-19 18:18 UTC, wmitsuda commented on src/useProvider.ts
> +  const probeOtsAPI = provider.send("ots_getApiLevel", []);
not sure if I understood, the check is made a few lines below inside the catch block

2024-06-19 18:22 UTC, wmitsuda commented
> I'm seeing this error appear in my console numerous times:
> 
> ```
> SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data  
> Home@http://localhost:5173/src/Home.tsx:28:44
> RenderedRoute@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:3633:7
> Outlet@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4070:20
> div
> ResolveAwait@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4239:7
> AwaitErrorBoundary@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4160:5
> Await@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4144:7
> Suspense
> ResolveAwait@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4239:7
> AwaitErrorBoundary@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4160:5
> Await@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4144:7
> ErrorBoundary@http://localhost:5173/node_modules/.vite/deps/react-error-boundary.js?v=2c06ec50:18:5
> Layout@http://localhost:5173/src/App.tsx:78:18
> RenderedRoute@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:3633:7
> RenderErrorBoundary@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:3590:5
> DataRoutes@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=2c06ec50:544:7
> Router@http://localhost:5173/node_modules/.vite/deps/chunk-DSEL6NC5.js?v=2c06ec50:4084:7
> RouterProvider@http://localhost:5173/node_modules/.vite/deps/react-router-dom.js?v=2c06ec50:361:7
> App
> _a@http://localhost:5173/node_modules/.vite/deps/react-helmet-async.js?v=2c06ec50:624:5
> ```

I really can't repro this one, how is your config done? any custom config.json or something like?

2024-06-19 22:20 UTC, sealer3 commented on src/useProvider.ts
> +  const probeOtsAPI = provider.send("ots_getApiLevel", []);
No error is throw if the API level is too low, since `provider.send("ots_getApiLevel", [])` does not throw an error if the response is, for example, 5 instead of 8.

2024-06-19 22:30 UTC, sealer3 commented
The console errors were due to a config issue on my end. I had `beaconAPI: null` for some reason.

2024-06-19 23:42 UTC, wmitsuda commented on src/useProvider.ts
> +  const probeOtsAPI = provider.send("ots_getApiLevel", []);
ah fuck, that's right :)

2024-06-20 01:00 UTC, sealer3 approved these changes

2024-06-20 01:00 UTC, sealer3 commented on src/useProvider.ts
> +    }
I pushed the change that fixes this.

2024-06-20 20:22 UTC, wmitsuda commented on src/useProvider.ts
> +    }
ahh, thanks, I think my brain was really not working well yesterday :)

anyway, I think if we need to add more checks to the probing code I'll want to undo the parallel probing because it is getting too complicated to understand.

2024-06-20 20:23 UTC, merged