Add whatsabi ABI filling prototype
otterscan/otterscan pull request #2237
Opened 2024-06-23 04:16 UTC by sealer3

Here's a preview:
![image](https://github.com/otterscan/otterscan/assets/125761775/01fc5cb2-c926-4366-8817-4638a682114a)

You can use the Read Contract tab, but the return values aren't decoded due to the function selector not using it and therefore 4bytes too: 
![image](https://github.com/otterscan/otterscan/assets/125761775/3674ae34-d9cc-4483-b633-b3f965537f55)

Function selectors not found in 4bytes aren't displayed currently.

Closes #2018

2024-06-24 01:01 UTC, sealer3 commented
Whatsabi seems to have minimal dependencies (only ethers), and I do not see any immediate risks to using it. It makes use of `node:fs` in its examples but does not refer to code that reads from the filesystem except in one of the debug tools.

I updated the code to show the unknown function signatures to give a more complete picture of the contract:
![image](https://github.com/otterscan/otterscan/assets/125761775/77fd0fff-e48f-4215-963b-73752cb3fdef)

I do not sort the unknown function selectors, but we might consider sorting them and the functions in the ABI.

2024-06-25 20:43 UTC, wmitsuda commented
I gave it a try and now I have mixed feelings:

- Nowadays most contracts seems to be verified on Sourcify (which is good)
- The ones who are not, they usually appear as "unknown selectors" for me (mainnet), which defeats totally the purpose of this feature. In fact, I've been browsing mainnet for 1/2 hour, randomly trying to find a non-verified contract that returns me the signatures, but all my attempts are "unknown".

So, maybe it is better to not implement this one, WDYT?

2024-06-26 05:48 UTC, sealer3 commented
There was a mistake in the 4bytes URL format (no 0x prefix should be used). I fixed this and also made the list of known functions sorted. Please try it again.

2024-06-28 01:59 UTC, wmitsuda commented
ah, now I see it correctly.

2024-06-28 02:03 UTC, wmitsuda requested changes

2024-06-28 02:03 UTC, wmitsuda commented on src/execution/address/Contracts.tsx
> +              of the ABI from its bytecode:
I think we can replace the ":" by a ".", since this is a warning inside a box, there no continuity from the warning to the ABI tree, so a ":" looks a little odd here.

2024-06-28 02:03 UTC, wmitsuda commented on src/sourcify/useSourcify.ts
> +export const useWhatsabiMetadata = (
does it make sense to separate whatsabi-related code into it own `.ts` file? so we don't mix Sourcify and whatsabi stuff and the code becomes more modular and clear in what are their connections.

2024-06-28 02:07 UTC, sealer3 commented on src/sourcify/useSourcify.ts
> +export const useWhatsabiMetadata = (
I agree.

2024-06-28 02:13 UTC, wmitsuda commented
> I do not sort the unknown function selectors, but we might consider sorting them and the functions in the ABI. Another thing to consider is that we don't know the state mutability of the functions. I set them all to `view` so you can try Read Contract on them.

ok, I think we can proceed to properly integrate it, I liked the result of the prototype so far, so let's make it a proper feature.

Having them on read contract is useful; yes it is impossible to know the return (if any) encoding or if they are mutable functions.

Some changes I think we should do from now:

1 - Add the same warning box in the "Read contract" tab so the user knows it is a guessed ABI
2 - Should we assume the return value is a blob of bytes and show the standard "Raw" textbox we show for `[]byte` so the user can at least examine and take their own conclusions about what is returned?

2024-06-28 02:15 UTC, wmitsuda commented
note to myself: I'm using the contract `0xB86E490E72F050c424383d514362Dc61DaBB1Cc3` on mainnet for testing because it has a good mix of unknown functions, known views and clearly non-view functions.

2024-06-28 02:35 UTC, sealer3 commented on src/sourcify/useSourcify.ts
> +export const useWhatsabiMetadata = (
I put the new file in the `sourcify` directory, since it shares many of the same types and functionality as `useSourcify`. Feel free to suggest an alternative.

2024-06-28 03:10 UTC, wmitsuda commented on src/sourcify/useSourcify.ts
> +export const useWhatsabiMetadata = (
we can move it later if we find a better organization

2024-06-28 04:23 UTC, sealer3 commented
We cannot have ethers interpret the return value as `bytes1[]` or similar because the contract ABI specification requires dynamic types to have the data length (in words) before the data. I've just disabled the Decoded tab for these return values.

2024-06-28 18:15 UTC, wmitsuda commented
> We cannot have ethers interpret the return value as `bytes1[]` or similar because the contract ABI specification requires dynamic types to have the data length (in words) before the data. I've just disabled the Decoded tab for these return values.

ah yes, that's what I meant to say, just the raw. and it is good that you left the "Decoded" button disabled instead of removing it because it clearly communicates the user the decoding is not available.

2024-06-28 18:25 UTC, wmitsuda approved these changes

2024-06-28 18:25 UTC, merged