Add ids and scrolling to Read Contract functions
otterscan/otterscan pull request #2261
Opened 2024-06-29 23:44 UTC by sealer3

Closes #2256

Note that there are no links on the React Contract page itself, but the functions can be linked to. @wmitsuda Do you want the numbers in the ordered list to be links?

2024-07-01 05:14 UTC, sealer3 commented
These are the links in the ABI to the Read Contract page:
![image](https://github.com/otterscan/otterscan/assets/125761775/c354c020-755d-4f1d-90c6-d15644e06a55)

The links are currently unstyled. I'd appreciate some suggestions on how they should look.

2025-01-03 19:42 UTC, wmitsuda commented
could you rebase this one as well? for some reason even checking out this code and running against erigon 3 is broken (it is working with erigon 2). not sure if there is something buggy in erigon 3 or something in otterscan which was fixed recently.

2025-01-03 19:43 UTC, wmitsuda commented
anyway, I think we can linkify the entire function - return string, e.g.:

"function blabla() view returns (address)"

2025-01-03 19:44 UTC, wmitsuda commented
I think we can style it with underline on hover + light blue text, but that's a guess, let's see how it looks like

2025-01-03 20:44 UTC, sealer3 commented
> could you rebase this one as well? for some reason even checking out this code and running against erigon 3 is broken (it is working with erigon 2). not sure if there is something buggy in erigon 3 or something in otterscan which was fixed recently.

This was fixed in a recent commit. Several Otterscan users were reporting issues with this, and switching from `latest` to `develop` fixed their problems.

2025-01-04 04:06 UTC, wmitsuda requested changes
just the styling pending

2025-01-04 23:49 UTC, sealer3 commented
@wmitsuda Done!

2025-01-05 22:36 UTC, wmitsuda approved these changes

2025-01-05 22:36 UTC, merged