Wrap block/position and from/nonce details
otterscan/otterscan pull request #2383
Opened 2024-07-29 05:33 UTC by sealer3

Closes #2380.

Allows the Block/Position and From/Nonce transaction detail rows to wrap.

Enough room:
![image](https://github.com/user-attachments/assets/ab1c9ef0-ee61-40a2-bb61-3e9c4f75cc31)

Compressed:
![image](https://github.com/user-attachments/assets/ae8d8bd0-9086-411e-b6e4-8d1201f4fd49)

2024-08-06 19:36 UTC, wmitsuda requested changes
hm, not sure if I like the solution, instead of simply allowing wrapping, I think we should:

- hide that vertical divider, which looks ugly when the second block gets wrapped.
- give some more vertical space between the wrapped blocks
- both blocks should be left aligned

2024-08-06 19:41 UTC, wmitsuda commented
also, as seen in the original issue screenshots, I think we should (independently of wrapping of not) make the individual components more resilient by:

- the "<<", ">>" navigation buttons should be made "not wrappable" regardless of their size
- the same for the "N confirmations" and "N / N" boxes

of course that would not solve this issue, it would actually make the entire row overflow or wrap by itself in this case, but I think it is worth it to apply those fixes as well.

2024-08-11 00:02 UTC, sealer3 commented
I have implemented everything listed except hiding the vertical divider when it is part of the first element in a new flex row. I spent a while trying to find an alternative that doesn't resort to using media queries for the viewport width, but there is no easy way of doing it. If it's any consolation, other top block explorers also have the vertical divider separating items between rows.

New vertical spacing example:
![image](https://github.com/user-attachments/assets/3cacd10b-c2ea-4dc9-ab1b-3b15bcfcb807)

2024-08-13 20:38 UTC, wmitsuda commented
> I have implemented everything listed except hiding the vertical divider when it is part of the first element in a new flex row. I spent a while trying to find an alternative that doesn't resort to using media queries for the viewport width, but there is no easy way of doing it. If it's any consolation, other top block explorers also have the vertical divider separating items between rows.
> 
> New vertical spacing example: ![image](https://private-user-images.githubusercontent.com/125761775/356842960-3cacd10b-c2ea-4dc9-ab1b-3b15bcfcb807.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1ODE3MzgsIm5iZiI6MTcyMzU4MTQzOCwicGF0aCI6Ii8xMjU3NjE3NzUvMzU2ODQyOTYwLTNjYWNkMTBiLWMyZWEtNGRjOS1hYjFiLTNiMTViY2ZjYjgwNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QyMDM3MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mN2ZjOTI0NzBhMTAxMDM3ZmEwY2NiYzc0NmQyODJmOTI4MmEzZmRkYTBkMDFjNjVlYjAxMDFlN2Q5ZmJlYzYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gx1fozasWX_bfChK0esrAni7F4YIE0OWp3IbWgt2U-A)

they are all ugly IMHO :)

but let's merge it, we can change it later in case of better ideas

2024-08-13 20:38 UTC, merged